sudo: required
dist: trusty
language: cpp

matrix:
  include:
    # XCode 6.4, OS X 10.10
    - env: MATRIX_EVAL="COMPILER=clang++ && BUILD_TYPE=Release"
      os: osx
      osx_image: xcode6.4
      compiler: clang

    # XCode 7.3, OS X 10.11
    - env: MATRIX_EVAL="COMPILER=clang++ && BUILD_TYPE=Release"
      os: osx
      osx_image: xcode7.3
      compiler: clang
      
      # Default OS X image for Travis (10.12, XCode 8.something)
    - env: MATRIX_EVAL="COMPILER=clang++ && BUILD_TYPE=Release"
      os: osx
      compiler: clang
